### ISSUE TITLE
GoogleCredentials.get_application_default is broken on App Engine due to #575

### ISSUE THREAD

**Issue by afterlastangel** [google/oauth2client#578]
After the PR #575. Our application on app engine has stopped working.
For example this command will give the error.
```
from oauth2client.client import GoogleCredentials
credentials = GoogleCredentials.get_application_default()
```

>   File "/............./vendors/oauth2client/client.py", line 1392, in _get_well_known_file
>     default_config_dir = os.path.join(os.path.expanduser('~'),
>   File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/posixpath.py", line 268, in expanduser
>     import pwd
> ImportError: No module named pwd

I filed an issue on Google Cloud Services Support about this problem already.

**Comment by jonparrott** [comment]
App Engine has fixed the pwd/os.path.expanduser issue but it has not yet been rolled out. Due to the nature of the App Engine release cycle, it might be 6 weeks or more before this is fixed upstream.

In the meantime, I recommend that you pin your version of oauth2client to something before that change was made, notably `<3.0.0`. 

@nathanielmanistaatgoogle do you think it's worthwhile for us to add a hacky workaround and cut a release for this?

**Comment by jonparrott** [comment]
(I'm leaving this bug open until I confirm that `os.path.expanduser` works in App Engine)

**Comment by afterlastangel** [comment]
Thanks @jonparrott I've changed the version to 2.0.0 and the problem was gone. So that I think the problem is related to your release of 3.0.0. The strange thing that App Engine supporter could not reproduce this problem on their testing environment.

**Comment by nathanielmanistaatgoogle** [comment]
@jonparrott: I'm open to it. How hacky and for how long in the codebase?

**Comment by jonparrott** [comment]
@nathanielmanistaatgoogle this hacky:

```
try:
    import pwd
except ImportError:
   pwd = None


...
well_known_path = ...

if pwd:
    well_known_path = os.path.expanduser(well_known_path)
```

etc.

It would live here for ~2-8 weeks, depending.

**Comment by jonparrott** [comment]
> So that I think the problem is related to your release of 3.0.0.

Yes, that's correct. In 3.0.0 we changed the resolution order to check for well-known files first. Pre-3.0.0, the App Engine service account was checked first - never calling the well-known file code that calls `os.path.expanduser`.

**Comment by nathanielmanistaatgoogle** [comment]
Sounds reasonable to me. Open an issue, `# TODO(<issue number>)` the hack, and release?

**Comment by jonparrott** [comment]
@nathanielmanistaatgoogle the alternative is to just tell GAE standard users to use `<3.0.0` until this is closed.

**Comment by nathanielmanistaatgoogle** [comment]
Who reads announcements anyway? :-P

More seriously: are those users going to need fixes and/or features implemented in this library in the next twelve weeks? At that point telling them to pin `<3.0.0` stops being an acceptable answer, right?

**Comment by jonparrott** [comment]
>  are those users going to need fixes and/or features implemented in this library in the next twelve weeks?

Doubtful.

There's also a workaround [here](https://github.com/GoogleCloudPlatform/gcloud-python/issues/2032#issuecomment-236226525).

**Comment by nathanielmanistaatgoogle** [comment]
I can live with that.

**Comment by jonparrott** [comment]
Let's leave it open until App Engine is fixed. I'll close.

**Comment by vit0r** [comment]
why don't use os.environ ? olders versions ?

**Comment by jonparrott** [comment]
> why don't use os.environ 

I'm not sure I understand what you mean.

**Comment by vit0r** [comment]
the files (project) in app GAE not allocated in $HOME or '~' the pwd not working... understand?

**Comment by jonparrott** [comment]
This should be fixed as of today.

**Comment by awh** [comment]
> This should be fixed as of today.

I just removed the 2.2.0 version pin on our app and redeployed it to GAE with the latest sdk (1.9.40) and it's still broken...

**Comment by jonparrott** [comment]
@awh is the stacktrace the same?

**Comment by danvuquoc** [comment]
@jonparrott I'm in the same situation, I had to pin the oauth2client==2.2.0. Letting it go to 3.0.0 does the following ... 

Here's the pip install of what got installed from the google-api-python-client:
```
pip install -t lib -r requirements.txt
Collecting google-api-python-client==1.5.2 (from -r requirements.txt (line 1))
  Using cached google_api_python_client-1.5.2-py2.py3-none-any.whl
Collecting six<2,>=1.6.1 (from google-api-python-client==1.5.2->-r requirements.txt (line 1))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting httplib2<1,>=0.8 (from google-api-python-client==1.5.2->-r requirements.txt (line 1))
  Using cached httplib2-0.9.2.zip
Collecting oauth2client<4.0.0,>=1.5.0 (from google-api-python-client==1.5.2->-r requirements.txt (line 1))
  Using cached oauth2client-3.0.0.tar.gz
Collecting uritemplate<1,>=0.6 (from google-api-python-client==1.5.2->-r requirements.txt (line 1))
  Using cached uritemplate-0.6.tar.gz
Collecting pyasn1>=0.1.7 (from oauth2client<4.0.0,>=1.5.0->google-api-python-client==1.5.2->-r requirements.txt (line 1))
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client<4.0.0,>=1.5.0->google-api-python-client==1.5.2->-r requirements.txt (line 1))
  Using cached pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client<4.0.0,>=1.5.0->google-api-python-client==1.5.2->-r requirements.txt (line 1))
  Using cached rsa-3.4.2-py2.py3-none-any.whl
Collecting simplejson>=2.5.0 (from uritemplate<1,>=0.6->google-api-python-client==1.5.2->-r requirements.txt (line 1))
  Using cached simplejson-3.8.2-cp27-cp27m-macosx_10_9_x86_64.whl
Installing collected packages: six, httplib2, pyasn1, pyasn1-modules, rsa, oauth2client, simplejson, uritemplate, google-api-python-client
  Running setup.py install for httplib2: started
    Running setup.py install for httplib2: finished with status 'done'
  Running setup.py install for oauth2client: started
    Running setup.py install for oauth2client: finished with status 'done'
  Running setup.py install for uritemplate: started
    Running setup.py install for uritemplate: finished with status 'done'
Successfully installed google-api-python-client-1.5.2 httplib2-0.9.2 oauth2client-3.0.0 pyasn1-0.1.9 pyasn1-modules-0.0.8 rsa-3.4.2 simplejson-3.8.2 six-1.10.0 uritemplate-0.6
```

And here is the trace:

```
ERROR    2016-08-26 17:53:41,891 webapp2.py:1552] No module named pwd
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/Users/danvuquoc/PhpstormProjects/tracker/app.py", line 190, in post
    credentials = GoogleCredentials.get_application_default()
  File "/Users/danvuquoc/PhpstormProjects/tracker/lib/oauth2client/client.py", line 1288, in get_application_default
    return GoogleCredentials._get_implicit_credentials()
  File "/Users/danvuquoc/PhpstormProjects/tracker/lib/oauth2client/client.py", line 1273, in _get_implicit_credentials
    credentials = checker()
  File "/Users/danvuquoc/PhpstormProjects/tracker/lib/oauth2client/client.py", line 1226, in _implicit_credentials_from_files
    credentials_filename = _get_well_known_file()
  File "/Users/danvuquoc/PhpstormProjects/tracker/lib/oauth2client/client.py", line 1392, in _get_well_known_file
    default_config_dir = os.path.join(os.path.expanduser('~'),
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 261, in expanduser
    import pwd
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/python/sandbox.py", line 963, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named pwd
```

**Comment by vit0r** [comment]
this operation expanduser('~') does not permited in GAE

**Comment by jonparrott** [comment]
A slight update to this: `os.expanduser` works on GAE, but not in the GAE SDK.
